version: "3.3"
services:
    web:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./content/www:/usr/share/nginx/content
        depends_on:
            - php
    php:
        build: ./php
        volumes:
            - ./content/www:/usr/share/nginx/content
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
          - ./content/:/content/
          - ./data:/var/lib/mysql
